### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by abhinavkashyap92** [Algomorph/pycvmpeg7#1]
Hi is there any documentation that I can access for this??

**Comment by Algomorph** [comment]
@abhinavkashyap92 sorry, I'm not supporting this project for a number of years now. Just keeping it around in case anyone wants the source. I believe that only some part of the MPEG-7 descriptor library were ported (the color structure descriptor), since that's specifically what I needed, but that should give enough of a start to anyone who wants to port the rest. I think some OpenCL-based SIMD parallelization was also added for the color structure, I'm not sure if it's here or not.
